package com.jin.eledger.dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.jin.eledger.pojo.EledgerPo;
import com.jin.eledger.pojo.EledgerVo;

@Repository
public interface LedgerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jin_ledger
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    int deleteByPrimaryKey(String ledgerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jin_ledger
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    int insert(EledgerPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jin_ledger
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    int insertSelective(EledgerPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jin_ledger
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    EledgerPo selectByPrimaryKey(String ledgerid);

    List<EledgerPo > selectByCase(EledgerVo eledgerVo);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jin_ledger
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(EledgerPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jin_ledger
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    int updateByPrimaryKey(EledgerPo record);
}