package com.jin.eledger.pojo;

import java.io.Serializable;
import java.util.Date;

public class EledgerPo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jin_ledger.ledgerId
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    private String ledgerId;
    private Byte status;//数据状态
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jin_ledger.tuzhibianhao
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    private String tuzhibianhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jin_ledger.tuzhimingcheng
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    private String tuzhimingcheng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jin_ledger.xingzhuang
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    private String xingzhuang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jin_ledger.guige
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    private String guige;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jin_ledger.cailiao
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    private Byte cailiao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jin_ledger.midu
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    private String midu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jin_ledger.shuliang
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    private Integer shuliang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jin_ledger.danjia
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    private String danjia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jin_ledger.tiji
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    private String tiji;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jin_ledger.zhongliang
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    private String zhongliang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jin_ledger.zongjia
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    private String zongjia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jin_ledger.IP
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jin_ledger.create_time
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jin_ledger.create_uesr
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    private String createUesr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jin_ledger.update_time
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jin_ledger
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jin_ledger.ledgerId
     *
     * @return the value of jin_ledger.ledgerId
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */


    public Byte getStatus() {
        return status;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jin_ledger.tuzhibianhao
     *
     * @return the value of jin_ledger.tuzhibianhao
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */


    public String getTuzhibianhao() {
        return tuzhibianhao;
    }

    public String getLedgerId() {
		return ledgerId;
	}

	public void setLedgerId(String ledgerId) {
		this.ledgerId = ledgerId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jin_ledger.tuzhibianhao
     *
     * @param tuzhibianhao the value for jin_ledger.tuzhibianhao
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    public void setTuzhibianhao(String tuzhibianhao) {
        this.tuzhibianhao = tuzhibianhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jin_ledger.tuzhimingcheng
     *
     * @return the value of jin_ledger.tuzhimingcheng
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    public String getTuzhimingcheng() {
        return tuzhimingcheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jin_ledger.tuzhimingcheng
     *
     * @param tuzhimingcheng the value for jin_ledger.tuzhimingcheng
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    public void setTuzhimingcheng(String tuzhimingcheng) {
        this.tuzhimingcheng = tuzhimingcheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jin_ledger.xingzhuang
     *
     * @return the value of jin_ledger.xingzhuang
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
	 

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jin_ledger.guige
     *
     * @return the value of jin_ledger.guige
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    public String getGuige() {
        return guige;
    }

    public String getXingzhuang() {
		return xingzhuang;
	}

	public void setXingzhuang(String xingzhuang) {
		this.xingzhuang = xingzhuang;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jin_ledger.guige
     *
     * @param guige the value for jin_ledger.guige
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    public void setGuige(String guige) {
        this.guige = guige;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jin_ledger.cailiao
     *
     * @return the value of jin_ledger.cailiao
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    public Byte getCailiao() {
        return cailiao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jin_ledger.cailiao
     *
     * @param cailiao the value for jin_ledger.cailiao
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    public void setCailiao(Byte cailiao) {
        this.cailiao = cailiao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jin_ledger.midu
     *
     * @return the value of jin_ledger.midu
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    public String getMidu() {
        return midu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jin_ledger.midu
     *
     * @param midu the value for jin_ledger.midu
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    public void setMidu(String midu) {
        this.midu = midu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jin_ledger.shuliang
     *
     * @return the value of jin_ledger.shuliang
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    public Integer getShuliang() {
        return shuliang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jin_ledger.shuliang
     *
     * @param shuliang the value for jin_ledger.shuliang
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    public void setShuliang(Integer shuliang) {
        this.shuliang = shuliang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jin_ledger.danjia
     *
     * @return the value of jin_ledger.danjia
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    public String getDanjia() {
        return danjia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jin_ledger.danjia
     *
     * @param danjia the value for jin_ledger.danjia
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    public void setDanjia(String danjia) {
        this.danjia = danjia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jin_ledger.tiji
     *
     * @return the value of jin_ledger.tiji
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    public String getTiji() {
        return tiji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jin_ledger.tiji
     *
     * @param tiji the value for jin_ledger.tiji
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    public void setTiji(String tiji) {
        this.tiji = tiji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jin_ledger.zhongliang
     *
     * @return the value of jin_ledger.zhongliang
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    public String getZhongliang() {
        return zhongliang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jin_ledger.zhongliang
     *
     * @param zhongliang the value for jin_ledger.zhongliang
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    public void setZhongliang(String zhongliang) {
        this.zhongliang = zhongliang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jin_ledger.zongjia
     *
     * @return the value of jin_ledger.zongjia
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    public String getZongjia() {
        return zongjia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jin_ledger.zongjia
     *
     * @param zongjia the value for jin_ledger.zongjia
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    public void setZongjia(String zongjia) {
        this.zongjia = zongjia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jin_ledger.IP
     *
     * @return the value of jin_ledger.IP
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jin_ledger.IP
     *
     * @param ip the value for jin_ledger.IP
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jin_ledger.create_time
     *
     * @return the value of jin_ledger.create_time
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jin_ledger.create_time
     *
     * @param createTime the value for jin_ledger.create_time
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jin_ledger.create_uesr
     *
     * @return the value of jin_ledger.create_uesr
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    public String getCreateUesr() {
        return createUesr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jin_ledger.create_uesr
     *
     * @param createUesr the value for jin_ledger.create_uesr
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    public void setCreateUesr(String createUesr) {
        this.createUesr = createUesr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jin_ledger.update_time
     *
     * @return the value of jin_ledger.update_time
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jin_ledger.update_time
     *
     * @param updateTime the value for jin_ledger.update_time
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jin_ledger
     *
     * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ledgerId=").append(ledgerId);
        sb.append(", tuzhibianhao=").append(tuzhibianhao);
        sb.append(", tuzhimingcheng=").append(tuzhimingcheng);
        sb.append(", xingzhuang=").append(xingzhuang);
        sb.append(", guige=").append(guige);
        sb.append(", cailiao=").append(cailiao);
        sb.append(", midu=").append(midu);
        sb.append(", shuliang=").append(shuliang);
        sb.append(", danjia=").append(danjia);
        sb.append(", tiji=").append(tiji);
        sb.append(", zhongliang=").append(zhongliang);
        sb.append(", zongjia=").append(zongjia);
        sb.append(", ip=").append(ip);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUesr=").append(createUesr);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}