package com.jin.eledger.pojo;

import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class EledgerVo {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column jin_ledger.ledgerId
	 *
	 * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
	 */
	private String ledgerId;
	private Byte status;//数据状态
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column jin_ledger.tuzhibianhao
	 *
	 * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
	 */
	private String tuzhibianhao;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column jin_ledger.tuzhimingcheng
	 *
	 * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
	 */
	private String tuzhimingcheng;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column jin_ledger.xingzhuang
	 *
	 * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
	 */
	private String xingzhuang;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column jin_ledger.guige
	 *
	 * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
	 */
	private String guige;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column jin_ledger.cailiao
	 *
	 * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
	 */
	private Byte cailiao;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column jin_ledger.midu
	 *
	 * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
	 */
	private String midu;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column jin_ledger.shuliang
	 *
	 * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
	 */
	private Integer shuliang;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column jin_ledger.danjia
	 *
	 * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
	 */
	private String danjia;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column jin_ledger.tiji
	 *
	 * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
	 */
	private String tiji;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column jin_ledger.zhongliang
	 *
	 * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
	 */
	private String zhongliang;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column jin_ledger.zongjia
	 *
	 * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
	 */
	private String zongjia;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column jin_ledger.IP
	 *
	 * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
	 */
	private String ip;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column jin_ledger.create_time
	 *
	 * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column jin_ledger.create_uesr
	 *
	 * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
	 */
	private String createUesr;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column jin_ledger.update_time
	 *
	 * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
	 */
	private Date updateTime;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database table jin_ledger
	 *
	 * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column jin_ledger.ledgerId
	 *
	 * @return the value of jin_ledger.ledgerId
	 *
	 * @mbggenerated Sun Oct 11 00:24:59 GMT+08:00 2020
	 */

	private String guige_desc;
	private String xingzhuang_desc;
	private String 	cailiao_desc;

	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date createTime_start;
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date createTime_end;


	public String getGuige_desc() {
		return guige_desc;
	}

	public void setGuige_desc(String guige_desc) {
		this.guige_desc = guige_desc;
	}

	public Byte getStatus() {
		return status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public Date getCreateTime_start() {
		return createTime_start;
	}
	public void setCreateTime_start(Date createTime_start) {
		this.createTime_start = createTime_start;
	}
	public Date getCreateTime_end() {
		return createTime_end;
	}
	public void setCreateTime_end(Date createTime_end) {
		this.createTime_end = createTime_end;
	}
	public String getXingzhuang_desc() {
		return xingzhuang_desc;
	}
	public void setXingzhuang_desc(String xingzhuang_desc) {
		this.xingzhuang_desc = xingzhuang_desc;
	}
	public String getCailiao_desc() {
		return cailiao_desc;
	}
	public void setCailiao_desc(String cailiao_desc) {
		this.cailiao_desc = cailiao_desc;
	}

 
	public String getLedgerId() {
		return ledgerId;
	}
	public void setLedgerId(String ledgerId) {
		this.ledgerId = ledgerId;
	}
	public String getTuzhibianhao() {
		return tuzhibianhao;
	}
	public void setTuzhibianhao(String tuzhibianhao) {
		this.tuzhibianhao = tuzhibianhao;
	}
	public String getTuzhimingcheng() {
		return tuzhimingcheng;
	}
	public void setTuzhimingcheng(String tuzhimingcheng) {
		this.tuzhimingcheng = tuzhimingcheng;
	}
 
	public String getGuige() {
		return guige;
	}
	public void setGuige(String guige) {
		this.guige = guige;
	}
 
	public String getXingzhuang() {
		return xingzhuang;
	}
	public void setXingzhuang(String xingzhuang) {
		this.xingzhuang = xingzhuang;
	}
	public Byte getCailiao() {
		return cailiao;
	}
	public void setCailiao(Byte cailiao) {
		this.cailiao = cailiao;
	}
	public String getMidu() {
		return midu;
	}
	public void setMidu(String midu) {
		this.midu = midu;
	}
	public Integer getShuliang() {
		return shuliang;
	}
	public void setShuliang(Integer shuliang) {
		this.shuliang = shuliang;
	}
	public String getDanjia() {
		return danjia;
	}
	public void setDanjia(String danjia) {
		this.danjia = danjia;
	}
	public String getTiji() {
		return tiji;
	}
	public void setTiji(String tiji) {
		this.tiji = tiji;
	}
	public String getZhongliang() {
		return zhongliang;
	}
	public void setZhongliang(String zhongliang) {
		this.zhongliang = zhongliang;
	}
	public String getZongjia() {
		return zongjia;
	}
	public void setZongjia(String zongjia) {
		this.zongjia = zongjia;
	}

	public String getIp() {
		return ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getCreateUesr() {
		return createUesr;
	}

	public void setCreateUesr(String createUesr) {
		this.createUesr = createUesr;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}
